In [8]:
import pandas as pd

df = pd.read_csv("../data/tweets.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11370 entries, 0 to 11369
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        11370 non-null  int64 
 1   keyword   11370 non-null  object
 2   location  7952 non-null   object
 3   text      11370 non-null  object
 4   target    11370 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 444.3+ KB


In [10]:
tweets = df["text"]

tweets.head()

0    Communal violence in Bhainsa, Telangana. "Ston...
1    Telangana: Section 144 has been imposed in Bha...
2    Arsonist sets cars ablaze at dealership https:...
3    Arsonist sets cars ablaze at dealership https:...
4    "Lord Jesus, your love brings freedom and pard...
Name: text, dtype: object

## TF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

VOCAB_SIZE = 1000

vectorizer = TfidfVectorizer(max_features=VOCAB_SIZE, use_idf=False)

X = vectorizer.fit_transform(tweets)

X

<11370x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 122207 stored elements in Compressed Sparse Row format>

In [12]:
X = X.toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
X[0, :]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.23570226,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.47140452, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [14]:
X.max()

1.0

In [15]:
X.mean()

0.0031213164358622316

In [16]:
tweets.iat[0]

'Communal violence in Bhainsa, Telangana. "Stones were pelted on Muslims\' houses and some houses and vehicles were set ablaze…'

In [17]:
[vectorizer.get_feature_names()[idx] for idx, value in enumerate(X[0, :]) if value > 0]

['ablaze', 'and', 'houses', 'in', 'on', 'set', 'some', 'violence', 'were']

## TF-IDF

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

VOCAB_SIZE = 1000

vectorizer = TfidfVectorizer(max_features=VOCAB_SIZE)

X = vectorizer.fit_transform(tweets)

X

<11370x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 122207 stored elements in Compressed Sparse Row format>

In [19]:
X = X.toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
X.max()

1.0

In [21]:
X.mean()

0.0029806796287371387

In [22]:
tweets.iat[0]

'Communal violence in Bhainsa, Telangana. "Stones were pelted on Muslims\' houses and some houses and vehicles were set ablaze…'

In [23]:
[vectorizer.get_feature_names()[idx] for idx, value in enumerate(X[0, :]) if value > 0]

['ablaze', 'and', 'houses', 'in', 'on', 'set', 'some', 'violence', 'were']

In [24]:
print(vectorizer.get_feature_names())

['00', '000', '01', '10', '100', '11', '12', '13', '14', '15', '20', '200', '2018', '2019', '2020', '24', '30', '40', '50', 'ablaze', 'able', 'about', 'absolutely', 'accident', 'account', 'across', 'act', 'action', 'activity', 'actually', 'affected', 'after', 'aftershock', 'again', 'against', 'ago', 'agree', 'air', 'airplane', 'al', 'alert', 'all', 'almost', 'alone', 'along', 'already', 'also', 'always', 'am', 'amazing', 'ambulance', 'america', 'american', 'americans', 'amp', 'an', 'and', 'animal', 'animals', 'annihilated', 'annihilation', 'another', 'anti', 'any', 'anyone', 'anything', 'apocalypse', 'ar', 'are', 'area', 'areas', 'aren', 'army', 'around', 'arrested', 'arson', 'article', 'as', 'ash', 'ask', 'asked', 'asking', 'ass', 'at', 'attack', 'attacked', 'australia', 'australian', 'avalanche', 'away', 'baby', 'back', 'backup', 'bad', 'bag', 'bagging', 'bags', 'bang', 'base', 'based', 'batangas', 'battle', 'bbc', 'bc', 'be', 'beat', 'because', 'become', 'been', 'before', 'behind', 

In [25]:
print(len(vectorizer.get_feature_names()))

1000
